<h1><center>Stock Analysis</center></h1>

Import necessary libraries

In [75]:
import pandas as pd
import numpy as np
import yfinance as yf
import matplotlib.pyplot as plt
import seaborn as sns
from alpha_vantage.timeseries import TimeSeries
from dotenv import load_dotenv
import os
import datetime

Import API and retrieve data

In [53]:
load_dotenv()

True

In [ ]:
# Imports data
ts = TimeSeries(os.getenv('api_key'), output_format='pandas')

df = ts.get_monthly_adjusted('QBTS')

stock = df[0]

In [ ]:
# Converts data into a pandas dataframe
stock = pd.DataFrame(stock)

In [ ]:
# View first five rows
stock.head()

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount
date,,,,,,,
2025-10-28,24.390,46.75,23.91,32.00,32.00,1.397237e+09,0.0
2025-09-30,15.155,29.18,14.78,24.71,24.71,1.144078e+09,0.0
2025-08-29,16.510,19.17,14.20,15.62,15.62,7.816219e+08,0.0
2025-07-31,15.200,20.56,14.29,17.19,17.19,1.006192e+09,0.0
2025-06-30,16.235,18.95,13.57,14.64,14.64,1.087715e+09,0.0

In [ ]:
# View colmns
stock.columns

Index(['1. open', '2. high', '3. low', '4. close', '5. adjusted close',
       '6. volume', '7. dividend amount'],
      dtype='object')

In [ ]:
# Rename columns
stock.rename(columns={'1. open': 'open', '2. high': 'high', '3. low': 'low', 
'4. close': 'close', '5. adjusted close': 'adj_close',
'6. volume': 'volume', '7. dividend amount': 'div_amt'}, inplace = True)

In [ ]:
# view first 5 rows to ensure column names changed.
stock.head()

              open   high    low  close  adj_close        volume  div_amt
date
2025-10-28  24.390  46.75  23.91  32.00      32.00  1.397237e+09      0.0
2025-09-30  15.155  29.18  14.78  24.71      24.71  1.144078e+09      0.0
2025-08-29  16.510  19.17  14.20  15.62      15.62  7.816219e+08      0.0
2025-07-31  15.200  20.56  14.29  17.19      17.19  1.006192e+09      0.0
2025-06-30  16.235  18.95  13.57  14.64      14.64  1.087715e+09      0.0

<h1><center>EDA</center><h1>

In [ ]:
# drop unnecessary column
stock.drop(columns=('div_amt'), inplace=True)

In [68]:
stock['pct_ch_adj'] = stock['adj_close'].pct_change() * 100

In [69]:
stock['pct_ch_adj'] = stock['pct_ch_adj'].round(2)

In [70]:
stock.head()

              open   high    low  close  adj_close        volume  pct_ch_adj
date
2025-10-28  24.390  46.75  23.91  32.00      32.00  1.397237e+09         NaN
2025-09-30  15.155  29.18  14.78  24.71      24.71  1.144078e+09      -22.78
2025-08-29  16.510  19.17  14.20  15.62      15.62  7.816219e+08      -36.79
2025-07-31  15.200  20.56  14.29  17.19      17.19  1.006192e+09       10.05
2025-06-30  16.235  18.95  13.57  14.64      14.64  1.087715e+09      -14.83

In [ ]:
trading_days = 252

rf_rate = 0.0381 # current 3 mth treasury yield
rfd_rate = rf_rate/trading_days
excess_returns = stock['close']-rfd_rate
rs_ratio = calculate_sharp_ratio

In [76]:
def calculate_sharp_ratio(ret, ann_rfr, periods):
    daily_rfr = ann_rfr/periods
    excess_ret = ret-daily_rfr
    mean_ex_ret = excess_ret.mean()
    std_ex_ret = excess_ret.std()

    if std_ex_ret == 0:
        return np.nan

    sharp_ratio = (mean_ex_ret/std_ex_ret) * np.sqrt(periods)

    return sharp_ratio

In [82]:
ann_rfr = 0.377
periods = 252
ret = stock['pct_ch_adj']
sharpe = calculate_sharp_ratio(ret, ann_rfr, periods).round(2)
print(f"The Sharpe ratio for QBTS is:\n{sharpe}")

The Sharpe ratio for QBTS is:
2.02